#!/usr/bin/env python
# WRC v1.1
# SYZYGY-DEV333
# Renders HTML5 webapps and runs them as standalones
# Apache Version 2

import os
import sys

from PyQt4.QtWebKit import QWebView
from PyQt4.QtGui import QApplication
from PyQt4.QtCore import QUrl

# CONFIG
load = 'Calculator.html'
# PROGRAM

app = QApplication(sys.argv)

browser = QWebView()
browser.load(QUrl(load))
browser.show()

app.exec_()
